import { ArrowLeft, ClipboardList, ClipboardPlus, FileLock2, HeartHandshake, MapPin, Phone, Plus, ShieldCheck } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useAuth } from '../auth/AuthContext';
import { hasPermission } from '../auth/permissions';
import { apiPost } from '../lib/api';
import { calculateAge, isValidThaiCid, normalizeCid } from '../lib/patientValidation';
import type { Patient, Visit, VisitListData } from '../types/api';

export function PatientDetailPage() {
  const { id='' }=useParams(); const {token,user}=useAuth(); const [patient,setPatient]=useState<Patient|null>(null); const [visits,setVisits]=useState<Visit[]>([]); const [error,setError]=useState(''); const [caregiverOpen,setCaregiverOpen]=useState(false); const [cidOpen,setCidOpen]=useState(false);
  const load=()=>Promise.all([apiPost<Patient>('patients.get',{patientId:id},token),apiPost<VisitListData>('visits.list',{patientId:id,page:1,pageSize:50},token)]).then(([patientData,visitData])=>{setPatient(patientData);setVisits(visitData.items);}).catch(e=>setError(e instanceof Error?e.message:'โหลดข้อมูลไม่สำเร็จ'));
  useEffect(()=>{void load();},[id,token]);
  if(error)return <div className="card text-red-700">{error}</div>; if(!patient)return <div className="card text-slate-500">กำลังโหลด…</div>;
  const age=calculateAge(patient.birthDate);
  return <div className="space-y-5"><div className="flex items-center justify-between"><Link to="/patients" className="inline-flex items-center gap-2 text-sm font-semibold text-brand-700"><ArrowLeft size={18}/>กลับทะเบียนผู้ป่วย</Link>{user&&(hasPermission(user.role,'visits.write')||hasPermission(user.role,'visits.draft'))&&<Link to={`/visits/new?patientId=${patient.patientId}`} className="flex min-h-11 items-center gap-2 rounded-2xl bg-brand-700 px-4 font-bold text-white"><ClipboardPlus size={18}/>เริ่มเยี่ยม</Link>}</div><section className="overflow-hidden rounded-3xl bg-gradient-to-br from-brand-700 to-emerald-500 p-6 text-white shadow-soft"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><span className="flex h-20 w-20 items-center justify-center rounded-3xl bg-white/20 text-3xl font-bold">{patient.firstName.slice(0,1)}</span><div className="flex-1"><p className="text-sm text-emerald-100">HN {patient.hn}</p><h1 className="mt-1 text-3xl font-bold">{patient.fullName}</h1><p className="mt-2 text-sm text-emerald-50">{age!==null?`${age} ปี · `:''}{patient.sexAtBirth||'ไม่ระบุเพศ'} · CID {patient.cidMasked||'ไม่ระบุ'}{!patient.cidMasked&&user&&hasPermission(user.role,'patients.write')&&<button onClick={()=>setCidOpen(true)} className="ml-2 rounded-lg bg-white/25 px-2 py-0.5 text-xs font-semibold hover:bg-white/35">+ เพิ่ม CID</button>}</p></div><span className="chip bg-white/20 text-white">{patient.riskLevel}</span></div></section>
    <div className="grid gap-5 lg:grid-cols-3"><section className="card lg:col-span-2"><h2 className="font-bold">ข้อมูลสุขภาพและการติดต่อ</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2"><Info label="การวินิจฉัยหลัก" value={patient.mainDiagnosis||'ไม่ระบุ'}/><Info label="สิทธิการรักษา" value={patient.coverageScheme||'ไม่ระบุ'}/><Info label="ประวัติแพ้" value={patient.allergies||'ไม่ระบุ'}/><Info label="สถานะ" value={patient.patientStatus}/><Info icon={Phone} label="โทรศัพท์" value={patient.phone||'ไม่ระบุ'}/><Info icon={MapPin} label="ที่อยู่" value={patient.addressText||'ไม่ระบุ'}/></dl></section><section className="card"><div className="flex items-center justify-between"><h2 className="font-bold">ผู้ดูแล</h2>{user&&hasPermission(user.role,'patients.write')&&<button onClick={()=>setCaregiverOpen(true)} className="rounded-xl bg-brand-50 p-2 text-brand-700" aria-label="เพิ่มผู้ดูแล"><Plus/></button>}</div><div className="mt-4 space-y-3">{patient.caregivers.length?patient.caregivers.map(c=><div key={c.caregiverId} className="rounded-2xl bg-slate-50 p-4"><div className="flex items-center gap-2"><HeartHandshake size={18} className="text-brand-700"/><p className="font-semibold">{c.firstName} {c.lastName}</p></div><p className="mt-1 text-sm text-slate-500">{c.relationshipCode} · {c.phone||'ไม่มีเบอร์โทร'}</p>{c.isPrimary&&<span className="chip mt-2 bg-brand-50 text-brand-700">ผู้ดูแลหลัก</span>}</div>):<p className="py-6 text-center text-sm text-slate-400">ยังไม่มีข้อมูลผู้ดูแล</p>}</div></section></div>
    <div className="grid gap-4 sm:grid-cols-2"><Link to={`/patients/${patient.patientId}/care`} className="card flex items-center gap-4 border-brand-100"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-brand-50 text-brand-700"><ClipboardList/></span><div><p className="font-bold">การดูแลต่อเนื่อง</p><p className="text-sm text-slate-500">ยา ปัญหา แผนดูแล ส่งต่อ และติดตาม</p></div></Link><Link to={`/patients/${patient.patientId}/documents`} className="card flex items-center gap-4 border-brand-100"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-brand-50 text-brand-700"><FileLock2/></span><div><p className="font-bold">เอกสารและ Consent</p><p className="text-sm text-slate-500">ไฟล์แนบส่วนตัวและความยินยอม</p></div></Link></div>
    <section className="card"><h2 className="font-bold">ประวัติการเยี่ยม</h2><div className="mt-5 border-l-2 border-brand-100 pl-5">{visits.length?visits.map(visit=><Link key={visit.visitId} to={`/visits/${visit.visitId}/edit`} className="relative mb-5 block rounded-2xl bg-slate-50 p-4"><span className="absolute -left-[29px] top-5 h-3 w-3 rounded-full bg-brand-600 ring-4 ring-white"/><div className="flex items-center justify-between gap-3"><div><p className="font-semibold">เยี่ยมครั้งที่ {visit.visitNo}</p><p className="text-sm text-slate-500">{visit.visitDate} · {visit.visitType}</p></div><span className={`chip ${visit.status==='SUBMITTED'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{visit.status}</span></div></Link>):<p className="pb-5 text-sm text-slate-400">ยังไม่มีประวัติการเยี่ยม</p>}</div></section>
    <section className="card flex items-center gap-3"><ShieldCheck className="text-brand-700"/><div><p className="font-semibold">ข้อมูลได้รับการควบคุมตามสิทธิ์</p><p className="text-sm text-slate-500">การเปิดดูข้อมูลผู้ป่วยครั้งนี้ถูกบันทึกใน Audit Log</p></div></section>{caregiverOpen&&<CaregiverDialog patientId={id} token={token} onClose={()=>setCaregiverOpen(false)} onCreated={()=>{setCaregiverOpen(false);load();}}/>}{cidOpen&&<SetCidDialog patientId={id} token={token} onClose={()=>setCidOpen(false)} onSaved={()=>{setCidOpen(false);load();}}/>}
  </div>;
}

function Info({label,value,icon:Icon}:{label:string;value:string;icon?:typeof Phone}){return <div><dt className="flex items-center gap-2 text-xs font-semibold uppercase text-slate-400">{Icon&&<Icon size={15}/>} {label}</dt><dd className="mt-1 font-medium">{value}</dd></div>}

function SetCidDialog({patientId,token,onClose,onSaved}:{patientId:string;token:string;onClose:()=>void;onSaved:()=>void}){const [cid,setCid]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();setError('');if(!isValidThaiCid(cid)){setError('เลขประจำตัวประชาชนไม่ผ่านการตรวจสอบ');return;}setBusy(true);try{await apiPost('patients.setCid',{patientId,cid:normalizeCid(cid)},token);onSaved();}catch(err){setError(err instanceof Error?err.message:'บันทึกไม่สำเร็จ');}finally{setBusy(false);}};return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-900/40 p-3"><form onSubmit={submit} className="w-full max-w-md rounded-3xl bg-white p-6"><h2 className="text-xl font-bold">เพิ่มเลขประจำตัวประชาชน</h2><p className="mt-1 text-sm text-slate-500">CID จะถูกเข้ารหัสด้วย Cloud KMS ก่อนจัดเก็บ · ต้องตั้งค่า KMS ให้เสร็จก่อน</p><label className="mt-4 block text-sm font-semibold">เลขประจำตัวประชาชน 13 หลัก<input value={cid} onChange={e=>setCid(e.target.value)} inputMode="numeric" className="mt-2 min-h-11 w-full rounded-2xl border border-slate-200 px-4"/></label>{error&&<p role="alert" className="mt-3 rounded-2xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="px-4">ยกเลิก</button><button disabled={busy} className="rounded-2xl bg-brand-700 px-5 py-3 font-bold text-white disabled:opacity-60">{busy?'กำลังบันทึก…':'บันทึก'}</button></div></form></div>;}

function CaregiverDialog({patientId,token,onClose,onCreated}:{patientId:string;token:string;onClose:()=>void;onCreated:()=>void}){const [form,setForm]=useState({firstName:'',lastName:'',phone:'',relationshipCode:'',isPrimary:true,livesTogether:true,consentToContact:true});const [error,setError]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();try{await apiPost('caregivers.add',{patientId,...form},token);onCreated();}catch(err){setError(err instanceof Error?err.message:'บันทึกไม่สำเร็จ')}};return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-900/40 p-3"><form onSubmit={submit} className="w-full max-w-lg rounded-3xl bg-white p-6"><h2 className="text-xl font-bold">เพิ่มผู้ดูแล</h2>{[['firstName','ชื่อ'],['lastName','นามสกุล'],['phone','เบอร์โทร'],['relationshipCode','ความสัมพันธ์']].map(([key,label])=><label key={key} className="mt-4 block text-sm font-semibold">{label}<input required={key!=='phone'} value={form[key as keyof typeof form] as string} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-2 min-h-11 w-full rounded-2xl border border-slate-200 px-4"/></label>)}<div className="mt-4 space-y-2 text-sm">{[['isPrimary','เป็นผู้ดูแลหลัก'],['livesTogether','อาศัยร่วมกัน'],['consentToContact','ยินยอมให้ติดต่อ']].map(([key,label])=><label key={key} className="flex items-center gap-3"><input type="checkbox" checked={form[key as keyof typeof form] as boolean} onChange={e=>setForm({...form,[key]:e.target.checked})}/>{label}</label>)}</div>{error&&<p className="mt-3 text-sm text-red-700">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} className="px-4">ยกเลิก</button><button className="rounded-2xl bg-brand-700 px-5 py-3 font-bold text-white">บันทึก</button></div></form></div>}
