import { ChevronRight, Plus, Search, ShieldCheck, UserRound, X } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../auth/AuthContext';
import { hasPermission } from '../auth/permissions';
import { apiPost } from '../lib/api';
import { isValidThaiCid, normalizeCid } from '../lib/patientValidation';
import type { Patient, PatientSearchData } from '../types/api';

export function PatientsPage() {
  const { token, user } = useAuth(); const [query, setQuery] = useState(''); const [items, setItems] = useState<Patient[]>([]);
  const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [open, setOpen] = useState(false);
  const load = async (value = query) => { setLoading(true); setError(''); try { const data=await apiPost<PatientSearchData>('patients.search',{query:value,page:1,pageSize:30},token);setItems(data.items);setTotal(data.total); } catch(e){setError(e instanceof Error?e.message:'โหลดข้อมูลไม่สำเร็จ');} finally{setLoading(false);} };
  useEffect(()=>{void load('');},[]);
  const search=(e:FormEvent)=>{e.preventDefault();void load();};
  return <div className="space-y-5"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-brand-700">Patient Registry</p><h1 className="text-3xl font-bold">ทะเบียนผู้ป่วย</h1><p className="mt-1 text-sm text-slate-500">ค้นหาด้วย HN, ชื่อ–นามสกุล หรือ CID</p></div>{user&&hasPermission(user.role,'patients.write')&&<button onClick={()=>setOpen(true)} className="flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-brand-700 px-5 font-bold text-white"><Plus size={19}/>เพิ่มผู้ป่วย</button>}</header>
    <form onSubmit={search} className="card flex gap-2"><div className="flex min-h-12 flex-1 items-center rounded-2xl bg-slate-50 px-4"><Search className="text-slate-400" size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full bg-transparent px-3 outline-none" placeholder="HN / ชื่อ / CID 13 หลัก" aria-label="ค้นหาผู้ป่วย"/></div><button className="rounded-2xl bg-slate-800 px-5 font-semibold text-white">ค้นหา</button></form>
    {error&&<p role="alert" className="rounded-2xl bg-red-50 p-4 text-red-700">{error}</p>}
    <section className="card p-0"><div className="flex items-center justify-between border-b border-slate-100 p-5"><h2 className="font-bold">รายชื่อผู้ป่วย</h2><span className="chip bg-brand-50 text-brand-700">{total} ราย</span></div>{loading?<div className="p-8 text-center text-slate-400">กำลังโหลด…</div>:items.length===0?<div className="p-10 text-center"><UserRound className="mx-auto text-slate-300" size={42}/><p className="mt-3 text-slate-500">ไม่พบข้อมูลผู้ป่วย</p></div>:<div className="divide-y divide-slate-100">{items.map(patient=><Link key={patient.patientId} to={`/patients/${patient.patientId}`} className="flex min-h-20 items-center gap-4 p-4 hover:bg-slate-50"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-brand-50 font-bold text-brand-700">{patient.firstName.slice(0,1)}</span><div className="min-w-0 flex-1"><p className="truncate font-bold">{patient.fullName}</p><p className="mt-1 text-sm text-slate-500">HN {patient.hn} · {patient.mainDiagnosis||'ไม่ระบุการวินิจฉัย'}</p></div><span className={`chip ${patient.riskLevel==='HIGH'||patient.riskLevel==='CRITICAL'?'bg-red-50 text-red-700':'bg-emerald-50 text-emerald-700'}`}>{patient.riskLevel}</span><ChevronRight className="text-slate-300"/></Link>)}</div>}</section>
    {open&&<CreatePatientDialog token={token} onClose={()=>setOpen(false)} onCreated={()=>{setOpen(false);void load('');}}/>}
  </div>;
}

function CreatePatientDialog({token,onClose,onCreated}:{token:string;onClose:()=>void;onCreated:()=>void}) {
  const [form,setForm]=useState({hn:'',cid:'',title:'',firstName:'',lastName:'',birthDate:'',sexAtBirth:'',phone:'',addressText:'',mainDiagnosis:'',allergies:'',coverageScheme:'',riskLevel:'LOW'}); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const change=(key:string,value:string)=>setForm(current=>({...current,[key]:value}));
  const submit=async(e:FormEvent)=>{e.preventDefault();setError('');if(form.cid&& !isValidThaiCid(form.cid)){setError('เลขประจำตัวประชาชนไม่ผ่านการตรวจสอบ');return;}setBusy(true);try{await apiPost('patients.create',{...form,cid:normalizeCid(form.cid)},token);onCreated();}catch(err){setError(err instanceof Error?err.message:'บันทึกไม่สำเร็จ');}finally{setBusy(false);}};
  const fields=[['hn','HN*'],['cid','เลขประจำตัวประชาชน (ไม่บังคับ)'],['firstName','ชื่อ*'],['lastName','นามสกุล*'],['birthDate','วันเกิด'],['phone','เบอร์โทร'],['mainDiagnosis','การวินิจฉัยหลัก'],['coverageScheme','สิทธิการรักษา']];
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-900/40 p-3 backdrop-blur-sm" role="dialog" aria-modal="true"><form onSubmit={submit} className="max-h-[94vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-bold">เพิ่มผู้ป่วย</h2><p className="text-sm text-slate-500">เว้นว่างเลขบัตร ปชช. ได้ · หากกรอกจะถูกเข้ารหัสด้วย Cloud KMS ก่อนจัดเก็บ</p></div><button type="button" onClick={onClose} className="p-3" aria-label="ปิด"><X/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{fields.map(([key,label])=><label key={key} className={key==='mainDiagnosis'?'sm:col-span-2':''}><span className="text-sm font-semibold">{label}</span><input type={key==='birthDate'?'date':'text'} required={label.endsWith('*')} value={form[key as keyof typeof form]} onChange={e=>change(key,e.target.value)} className="mt-2 min-h-12 w-full rounded-2xl border border-slate-200 px-4 outline-none focus:ring-2 focus:ring-brand-500"/></label>)}<label><span className="text-sm font-semibold">เพศกำเนิด</span><select value={form.sexAtBirth} onChange={e=>change('sexAtBirth',e.target.value)} className="mt-2 min-h-12 w-full rounded-2xl border border-slate-200 px-4"><option value="">ไม่ระบุ</option><option value="MALE">ชาย</option><option value="FEMALE">หญิง</option><option value="OTHER">อื่น ๆ</option></select></label><label><span className="text-sm font-semibold">ระดับความเสี่ยง</span><select value={form.riskLevel} onChange={e=>change('riskLevel',e.target.value)} className="mt-2 min-h-12 w-full rounded-2xl border border-slate-200 px-4"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><label className="sm:col-span-2"><span className="text-sm font-semibold">ที่อยู่</span><textarea value={form.addressText} onChange={e=>change('addressText',e.target.value)} className="mt-2 min-h-24 w-full rounded-2xl border border-slate-200 p-4"/></label></div>{error&&<p role="alert" className="mt-4 rounded-2xl bg-red-50 p-3 text-red-700">{error}</p>}<div className="mt-6 flex items-center justify-between"><p className="flex items-center gap-2 text-xs text-slate-500"><ShieldCheck size={16}/>ข้อมูลอ่อนไหวไม่ถูกบันทึกใน log</p><button disabled={busy} className="min-h-12 rounded-2xl bg-brand-700 px-7 font-bold text-white disabled:opacity-60">{busy?'กำลังบันทึก…':'บันทึกผู้ป่วย'}</button></div></form></div>;
}
